adventure_works_analytics:
  target: prod
  outputs:
    prod:
      type: databricks
      host: dbc-da48dd52-1138.cloud.databricks.com
      http_path: /sql/1.0/warehouses/7fc19b05d6292008
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      catalog: ted_dev
      schema: dev_diego_brito
      threads: 4
      keepalives_idle: 240
      search_path: "{{ env_var('DBT_DATABRICKS_SEARCH_PATH', 'ted_dev') }}"