name: 'adventure_works_analytics'
version: '1.0.0'
config-version: 2

profile: 'adventure_works_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  adventure_works_analytics:
    staging:
      +materialized: view
      +schema: staging
      +docs:
        show: true
      sales:
        +materialized: view
        +schema: staging
      customers:
        +materialized: view
        +schema: staging
      employees:
        +materialized: view
        +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
      +docs:
        show: true
    marts:
      +materialized: table
      +schema: marts
      +docs:
        show: true
      dimensions:
        +materialized: table
        +schema: dimensions
        +docs:
          show: true
      facts:
        +materialized: table
        +schema: facts
        +docs:
          show: true
      # Convenções de nomenclatura dbt
      # stg_ = staging models (dados limpos e padronizados)
      # int_ = intermediate models (transformações e agregações)
      # dim_ = dimension tables (dimensões do data warehouse)
      # fact_ = fact tables (fatos e métricas transacionais)

vars:
  raw_schema: "ted_dev.dev_diego_brito"
