adventure_works_analytics:
  outputs:
    dev:
      type: databricks
      catalog: ted_dev
      schema: dev_diego_brito
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 4
      connect_retries: 3
      connect_timeout: 60
      retry_all: true
      compute:
        type: serverless
      
    prod:
      type: databricks
      catalog: ted_prod
      schema: prod_diego_brito
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 8
      connect_retries: 5
      connect_timeout: 120
      retry_all: true
      compute:
        type: serverless
  
  target: dev